name: Helm Chart - Publish - CI pipeline

on:
  push:
    branches:
      - main # Main branch name
    paths:
      - "*-chart/**" # Trigger only on changes in each dir that ends with -chart

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git tags

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0 # Pin the appropriate stable version

      - name: Get Chart Name
        id: get-chart-name
        run: |
          CHART_DIR=$(ls -d */ | grep -vE '^\.' | head -n 1) # Get the first directory
          echo "CHART_DIR=$CHART_DIR" >> "$GITHUB_OUTPUT"

      - name: Lint Helm Chart
        run: |
          helm lint ${{ steps.get-chart-name.outputs.CHART_DIR }} --ignore-path backup

      - name: Set up Docker config
        run: |
          mkdir -p ~/.docker
          echo '${{ secrets.DOCKER_CONFIG }}' | base64 -d > ~/.docker/config.json
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Package Helm Chart
        run: |
          helm package ${{ steps.get-chart-name.outputs.CHART_DIR }}

      - name: Push Helm Chart to OCI
        run: |
          CHART_NAME=$(yq e '.name' ${{ steps.get-chart-name.outputs.CHART_DIR }}/Chart.yaml | tr -d '"')
          CHART_VERSION=$(yq e '.version' ${{ steps.get-chart-name.outputs.CHART_DIR }}/Chart.yaml | tr -d '"')
          echo "CHART NAME: $CHART_NAME"
          echo "CHART VERSION: $CHART_VERSION"
          echo "CHART_NAME=$CHART_NAME" > chart_info.txt
          echo "CHART_VERSION=$CHART_VERSION" >> chart_info.txt
          helm push ./${CHART_NAME}-$CHART_VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}