name: Publish Helm Chart to OCI

on:
  push:
    branches:
      - main
    paths:
      - "my-chart/**" # Trigger only on changes in the my-chart dir

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git tags

      - name: Set up Helm
        uses: actions/setup-helm@v3
        with:
          version: "v3.13.3" # Or the version you need

      - name: Set up Docker config
        run: |
          mkdir -p ~/.docker
          echo '${{ secrets.DOCKER_CONFIG }}' | base64 -d > ~/.docker/config.json
          chmod 600 ~/.docker/config.json
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Package Helm Chart
        run: |
          # cd charts/my-chart # Removed
          helm package my-chart/ # Corrected path

      - name: Push Helm Chart to OCI
        run: |
          # cd charts/my-chart # Removed
          # set the tag
          CHART_VERSION=$(yq e '.version' my-chart/Chart.yaml) # Corrected path
          echo "CHART VERSION: $CHART_VERSION"
          helm chart push ./my-chart-$CHART_VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-chart:v$CHART_VERSION # Corrected path
