name: Helm Chart CI

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Prepare local Helm repo
      run: |
        mkdir -p $HOME/local-helm-repo
        helm lint my-sample-chart
        helm package my-sample-chart --destination $HOME/local-helm-repo
        helm repo index $HOME/local-helm-repo --url http://localhost:8080
        helm repo add local-repo http://localhost:8080 || true
        helm repo update

    - name: Helm Upgrade (dry run)
      run: |
        helm upgrade --install my-release local-repo/my-sample-chart --dry-run
