name: Publish Helm Chart to OCI

on:
  push:
    branches:
      - main # Main branch name
    paths:
      - "my-chart/**" # Trigger only on changes in the my-chart dir

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git tags

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0 # Pin the appropriate stable version

      - name: Lint Helm Chart
        run: |
          helm lint my-chart/    

      - name: Set up Docker config
        run: |
          mkdir -p ~/.docker
          echo '${{ secrets.DOCKER_CONFIG }}' | base64 -d > ~/.docker/config.json
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Package Helm Chart
        run: |
          helm package my-chart/ # Corrected path

      - name: Push Helm Chart to OCI
        run: |
          # cd charts/my-chart # Removed
          # set the tag
          CHART_VERSION=$(yq e '.version' my-chart/Chart.yaml | tr -d '"') # Corrected path
          echo "CHART VERSION: $CHART_VERSION"
          helm push ./my-chart-$CHART_VERSION.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }} # Corrected path
          

