name: Helm Chart - Deploy - CD pipeline

#on:
#  workflow_run:
#    workflows: ["Helm Chart - Publish - CI pipeline"]
#    types:
#      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm Registry Login
        run: |
          echo '${{ secrets.DOCKER_CONFIG }}' | base64 -d > ~/.docker/config.json
          helm registry login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} registry-1.docker.io

      - name: Get Chart Name and Version from CI Workflow
        id: get-chart-info
        run: |
          CHART_NAME=$(cat $GITHUB_WORKSPACE/chart_info.txt | grep CHART_NAME | cut -d'=' -f2)
          CHART_VERSION=$(cat $GITHUB_WORKSPACE/chart_info.txt | grep CHART_VERSION | cut -d'=' -f2)
          echo "CHART_NAME=$CHART_NAME" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_OUTPUT"

      - name: Pull Helm Chart from OCI using Helm
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          helm pull oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.get-chart-info.outputs.CHART_NAME }} --version ${{ steps.get-chart-info.outputs.CHART_VERSION }}
          ls -l

      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }} # Add KUBECONFIG as secret in Github

      - name: Show current Kubernetes context
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Template Helm chart
        run: |
          helm template my-release ./${{ steps.get-chart-info.outputs.CHART_NAME }}-${{ steps.get-chart-info.outputs.CHART_VERSION }}.tgz \
            --namespace default \
            --set image.repository=registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.get-chart-info.outputs.CHART_NAME }} \
            --set image.tag=${{ steps.get-chart-info.outputs.CHART_VERSION }} \
            > rendered.yaml

      - name: Deploy rendered manifests
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            rendered.yaml
          namespace: default
          pull-images: true
          strategy: basic
          route-method: service
          version-switch-buffer: 0
          traffic-split-method: pod
          percentage: 0
          force: false
          annotate-namespace: true
          private-cluster: false
          skip-tls-verify: false